// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlfflvjnlrnckzpvojwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZmZsdmpubHJuY2t6cHZvand5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzE2NDYsImV4cCI6MjA2MzI0NzY0Nn0.57ukGhOWcYrDnhNOSTd7B6rV6Z1AwL139mk_NWCYbmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);